trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.12345)'  # Utilise l'ID de build comme tag

stages:
- stage: Build
  displayName: Build and Push Images
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    # Étape 1 : Connexion à Docker Hub
    - script: |
        echo "Logging in to Docker Hub"
        docker login -u $(DOCKER_HUB_USERNAME) -p $(DOCKER_HUB_PASSWORD)
      displayName: 'Login to Docker Hub'

    # Étape 2 : Construire et pousser les images avec Docker Compose
    - script: |
        echo "Building and pushing images with Docker Compose"
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push
      displayName: 'Build and Push Images with Docker Compose'