
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: AnasDBB
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - app-network

  backend:
    build: ./backend
    image: ${DOCKER_USERNAME}/task-management-backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/AnasDBB?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build: ./frontend
    image: ${DOCKER_USERNAME}/task-management-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
