name: Build and deploy JAR app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Backend
        run: |
          cd backend
          ./mvnw clean package -DskipTests
        env:
          SPRING_PROFILES_ACTIVE: prod

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '10.x'
          cache: 'npm'

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm install -g @angular/cli@7.3.9
          ng build --prod
        
      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: '${{ github.workspace }}/backend/target/*.jar'

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: '${{ github.workspace }}/frontend/dist'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-jar
          
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tesss'
          slot-name: 'Production'
          package: '*.jar'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_415C1747C2E749159AB1D8CEF6B02494 }}
