name: Build and deploy JAR app and Angular frontend to Azure Web App - test25

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      # Set up Java for backend
      - name: Set up Java version
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      # Build backend with Maven
      - name: Build backend with Maven
        run: mvn clean install
        working-directory: backend

      # Upload backend artifact
      - name: Upload backend artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/backend/target/*.jar'

      # Set up Node.js for frontend
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '10.24.1'

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      # Build frontend with Angular CLI
      - name: Build frontend with Angular CLI
        run: npm run build
        working-directory: frontend

      # Upload frontend artifact
      - name: Upload frontend artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: angular-app
          path: '${{ github.workspace }}/frontend/dist'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Download backend artifact
      - name: Download backend artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      # Download frontend artifact
      - name: Download frontend artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: angular-app

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'test25'
          slot-name: 'staging'
          package: '*.jar'
          publish-profile: |
            <?xml version="1.0" encoding="utf-8"?>
            <publishData>
              <publishProfile profileName="test25-staging - Web Deploy" publishMethod="MSDeploy" publishUrl="test25-staging-byfzheeehjbjdjdt.scm.francecentral-01.azurewebsites.net:443" msdeploySite="test25__staging" userName="$test25__staging" userPWD="u75unmYyKX7QibL8gBlxZbEQsp7Jcz2NDf6HsKK8lrwen5h0Wjyxcn0Ckiiv" destinationAppUrl="http://test25-staging-byfzheeehjbjdjdt.francecentral-01.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites">
                <databases />
              </publishProfile>
            </publishData>
