name: Build and deploy Angular frontend to Azure Web App - test25

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install --legacy-peer-deps
          npm install fullcalendar@4.0.0-alpha.4 --legacy-peer-deps

      - name: Build frontend with Angular
        run: |
          cd frontend
          npm run build -- --configuration=production

      - name: Upload frontend build folder
        uses: actions/upload-artifact@v4
        with:
          name: frontend-app
          path: frontend/dist/frontend/*
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-frontend.outputs.webapp-url }}
      
    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-app
          path: frontend-dist

      - name: Deploy to Azure Web App
        id: deploy-frontend
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'test25'
          slot-name: 'staging'
          package: frontend-dist
          publish-profile: |
            <?xml version="1.0" encoding="utf-8"?>
            <publishData>
              <publishProfile profileName="test25-staging - Web Deploy" publishMethod="MSDeploy" publishUrl="test25-staging-byfzheeehjbjdjdt.scm.francecentral-01.azurewebsites.net:443" msdeploySite="test25__staging" userName="$test25__staging" userPWD="u75unmYyKX7QibL8gBlxZbEQsp7Jcz2NDf6HsKK8lrwen5h0Wjyxcn0Ckiiv" destinationAppUrl="http://test25-staging-byfzheeehjbjdjdt.francecentral-01.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites">
                <databases />
              </publishProfile>
            </publishData>
