# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - testP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_63073c894d7743e79faf5f332f7511de }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ab09efb0c56d4c9799958af216f5850e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_63073c894d7743e79faf5f332f7511de }}/diabanas/task-management-frontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'testP'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ada40a6a9efe4c1ebcce222458b4345c }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_63073c894d7743e79faf5f332f7511de }}/diabanas/task-management-frontend:${{ github.sha }}'