name: Build and deploy JAR app and Angular frontend to Azure Web App - test25

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      # Setup Java (Backend)
      - name: Set up Java version
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      # Build Backend with Maven
      - name: Build with Maven
        run: mvn clean install
        working-directory: backend

      # Setup Node.js (Frontend)
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '10.24.1'

      # Install dependencies for frontend
      - name: Install dependencies for frontend
        run: npm install
        working-directory: frontend

      # Install fullcalendar package to avoid the error
      - name: Install fullcalendar dependency
        run: npm install fullcalendar
        working-directory: frontend

      # Update caniuse-lite to avoid warnings
      - name: Update caniuse-lite
        run: npm update caniuse-lite
        working-directory: frontend

      # Build frontend with Angular
      - name: Build frontend with Angular
        run: npm run build --prod
        working-directory: frontend

      # Upload artifact for deployment job
      - name: Upload backend artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/backend/target/*.jar'

      - name: Upload frontend build folder for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: frontend-app
          path: '${{ github.workspace }}/frontend/dist/*'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:
      - name: Download backend artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Download frontend artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: frontend-app

      # Deploy to Azure Web App (Backend)
      - name: Deploy to Azure Web App (Backend)
        id: deploy-backend
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'test25'
          slot-name: 'staging'
          package: '*.jar'
          publish-profile: |
            <?xml version="1.0" encoding="utf-8"?>
            <publishData>
              <publishProfile profileName="test25-staging - Web Deploy" publishMethod="MSDeploy" publishUrl="test25-staging-byfzheeehjbjdjdt.scm.francecentral-01.azurewebsites.net:443" msdeploySite="test25__staging" userName="$test25__staging" userPWD="u75unmYyKX7QibL8gBlxZbEQsp7Jcz2NDf6HsKK8lrwen5h0Wjyxcn0Ckiiv" destinationAppUrl="http://test25-staging-byfzheeehjbjdjdt.francecentral-01.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites">
                <databases />
              </publishProfile>
            </publishData>

      # Deploy to Azure Web App (Frontend)
      - name: Deploy to Azure Web App (Frontend)
        id: deploy-frontend
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'test25'
          slot-name: 'staging'
          package: 'frontend-app'
          publish-profile: |
            <?xml version="1.0" encoding="utf-8"?>
            <publishData>
              <publishProfile profileName="test25-staging - Web Deploy" publishMethod="MSDeploy" publishUrl="test25-staging-byfzheeehjbjdjdt.scm.francecentral-01.azurewebsites.net:443" msdeploySite="test25__staging" userName="$test25__staging" userPWD="u75unmYyKX7QibL8gBlxZbEQsp7Jcz2NDf6HsKK8lrwen5h0Wjyxcn0Ckiiv" destinationAppUrl="http://test25-staging-byfzheeehjbjdjdt.francecentral-01.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites">
                <databases />
              </publishProfile>
            </publishData>
